### ISSUE TITLE
Merge pull request #20 from coinotc/hjc

### ISSUE THREAD

**Issue by kenken64** [coinotc/coinotc-svr#22]
We having issue on the merge pull for #20 where dotenv is removed?

Why is .env.sample file also removed?

**Comment by kenken64** [comment]
![image](https://user-images.githubusercontent.com/631205/37550871-1c1faf5e-29d0-11e8-8a6c-27ee68581d7c.png)

![image](https://user-images.githubusercontent.com/631205/37550875-357ff1fc-29d0-11e8-9687-2ca5709a3b6f.png)

**Comment by Mr-Mooo** [comment]
fix in the #23
